// THIS FILE IS GENERATED BY 'npm run set-env-variables'

export const environment = {
  production: true,

  // Feature-switches:
  isDebug: false,
  showDebug: false,
  useAnimation: true,

  // APIs:
  url_121_service_api: '',

  // Google Sheets API:
  google_sheets_api_url: 'https://sheets.googleapis.com/v4/spreadsheets',
  google_sheets_sheet_id: '1OANMuGJxGBQ2ba3xVfKvTpD0EGQM-ukUrgRyN9tzMbQ',
  google_sheets_api_key: 'AIzaSyCJW0xxT4kgdUIzVGBVu3X39QxYrYBLzdY',
};
